export const GET_LIST_MOVIES = "GET_LIST_MOVIES";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const SET_TEXT = 'SET_TEXT'
export const SET_OPEN_TOP_MODAL = "SET_OPEN_TOP_MODAL"
export const SET_CLOSE_TOP_MODAL = "SET_CLOSE_TOP_MODAL"
export const SAVE_INFO_USER = "SAVE_INFO_USER"
export const CLEAR_INFO_USER = "CLEAR_INFO_USER"
export const REFESH_TOKEN_SUCCESS = "REFESH_TOKEN_SUCCESS"
export const LOGOUT = "LOGOUT"
export const UPDATE_INFO_SINGLE = "UPDATE_INFO_SINGLE"
export const SAVE_AGE = "SAVE_AGE"
export const LOADING = "LOADING"
export const LOADING_SUCCESS = "LOADING_SUCCESS"

export const SET_IS_HAVE_NEW_NOTI = "SET_IS_HAVE_NEW_NOTI"
export const SET_CLEAR_NOTI = "SET_CLEAR_NOTI"

// vé mời
export const SET_BADGE_TICKET = "SET_BADGE_TICKET"
export const SET_BADGE_TICKET_INC = "SET_BADGE_TICKET_INC"
export const CLEAR_BADGE_TICKET = "CLEAR_BADGE_TICKET"

// lời mời
export const SET_BADGE_INVITATION = "SET_BADGE_INVITATION"
export const SET_BADGE_INVITATION_INC = "SET_BADGE_INVITATION_INC"
export const CLEAR_BADGE_INVITATION = "CLEAR_BADGE_INVITATION"
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS"
export const UPDATE_CART = "UPDATE_CART"


// DOANH THU
export const SAVE_LIST_REVENUE_BRANCH = "SAVE_LIST_REVENUE_BRANCH"
export const SAVE_LIST_REVENUE_SERVICE = "SAVE_LIST_REVENUE_SERVICE"
export const SAVE_LIST_COST_PART = "SAVE_LIST_COST_PART"
export const SAVE_LIST_COST_ITEM = "SAVE_LIST_COST_ITEM"
export const MODAL_MONEY_FLOW = "MODAL_MONEY_FLOW"
export const SAVE_LIST_FLOW_MONEY = "SAVE_LIST_FLOW_MONEY"

// MODAL FILTER
export const OPEN_MODAL_FILTER = 'OPEN_MODAL_FILTER'
export const CLOSE_MODAL_FILTER = 'CLOSE_MODAL_FILTER'
export const UPDATE_DATE_FILTER = 'UPDATE_DATE_FILTER'
export const LOADING_BEGIN = 'LOADING_BEGIN'
export const LOADING_DONE = 'LOADING_DONE'

// NETWORK
export const NETWORK_ERROR = 'NETWORK_ERROR'

// TASK
export const TAB_RIGHT_NOTIFI_TASK = "TAB_RIGHT_NOTIFI_TASK"
export const MODAL_CREATE_TASK = 'MODAL_CREATE_TASK'
export const SET_TITLE_CREATE_TASK = 'SET_TITLE_CREATE_TASK'
export const SET_DESCRIPTION_CREATE_TASK = 'SET_DESCRIPTION_CREATE_TASK'
export const ADD_MEMBER_TO_TASK = 'ADD_MEMBER_TO_TASK'
export const REMOVE_MEMBER_TO_TASK = 'REMOVE_MEMBER_TO_TASK'
export const SET_DEADLINE_TASK = 'SET_DEADLINE_TASK'
export const ADD_MINI_TASK = 'ADD_MINI_TASK'
export const REMOVE_MINI_TASK = 'REMOVE_MINI_TASK'
export const SET_DONE_MINI_TASK = 'SET_DONE_MINI_TASK'
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const SET_CURR_SEE_TASK_DETAIL = 'SET_CURR_SEE_TASK_DETAIL'
export const PICK_LEADER_TASK = 'PICK_LEADER_TASK'
export const GET_ALL_TASK = 'GET_ALL_TASK'
export const ADD_NEW_SUBTASK = 'ADD_NEW_SUBTASK'
export const SAVE_INFO_CURR_TASK_EDIT = 'SAVE_INFO_CURR_TASK_EDIT'
export const SAVE_INFO_CURR_TASK_SEE = 'SAVE_INFO_CURR_TASK_SEE'
export const SET_CURR_TASK_EDIT_NAME = 'SET_CURR_TASK_EDIT_NAME'
export const SET_CURR_TASK_EDIT_DESCRIPTION = 'SET_CURR_TASK_EDIT_DESCRIPTION'
export const ADD_MEMBER_TO_EDIT_TASK = 'ADD_MEMBER_TO_EDIT_TASK'
export const REMOVE_MEMBER_TO_EDIT_TASK = 'REMOVE_MEMBER_TO_EDIT_TASK'
export const PICK_LEADER_EDIT_TASK = 'PICK_LEADER_EDIT_TASK'
export const SET_DEADLINE_EDIT_TASK = 'SET_DEADLINE_EDIT_TASK'
export const SET_DONE_MINI_EDIT_TASK = 'SET_DONE_MINI_EDIT_TASK'
export const REMOVE_MINI_EDIT_TASK = 'REMOVE_MINI_EDIT_TASK'
export const SET_DONE_SUB_TASK_SEE = 'SET_DONE_SUB_TASK_SEE'
export const REMOVE_SUB_TASK_SEE = 'REMOVE_SUB_TASK_SEE'
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK'
export const SET_MY_TASKS_NOT_STARTED = 'SET_MY_TASKS_NOT_STARTED'
export const SET_MY_TASKS_NOT_STARTED_MORE = 'SET_MY_TASKS_NOT_STARTED_MORE'
export const SET_MY_TASKS_IN_PROGRESS = 'SET_MY_TASKS_IN_PROGRESS'
export const SET_MY_TASKS_IN_PROGRESS_MORE = 'SET_MY_TASKS_IN_PROGRESS_MORE'
export const SET_MY_TASKS_COMPLETED = 'SET_MY_TASKS_COMPLETED'
export const SET_MY_TASKS_COMPLETED_MORE = 'SET_MY_TASKS_COMPLETED_MORE'
export const UPDATE_TASK_AFTER_EDIT = 'UPDATE_TASK_AFTER_EDIT'
// export const NEW_TASK_HAS_STARTED='NEW_TASK_HAS_STARTED'
export const NEW_TASK_HAS_CHANGE_STATUS = 'NEW_TASK_HAS_CHANGE_STATUS'
export const NEW_TASK_HAS_UPDATED = 'NEW_TASK_HAS_UPDATED'
export const CLEAR_DATA_AFTER_CREATE_TASK = 'CLEAR_DATA_AFTER_CREATE_TASK'
export const NEW_ASSIGN_TASK = 'NEW_ASSIGN_TASK'
export const NEW_TASK_HAS_REMOVED = 'NEW_TASK_HAS_REMOVED'


// NOTIFICATION
export const SET_NOTIFICATION_FOR_TASK = "SET_NOTIFICATION_FOR_TASK"
export const SET_NOTIFICATION_FOR_POST = "SET_NOTIFICATION_FOR_POST"
export const NEW_NOTIFICATION_HAS_COME_FOR_TASK = "NEW_NOTIFICATION_HAS_COME_FOR_TASK"
export const NEW_NOTIFICATION_HAS_COME_FOR_POST = "NEW_NOTIFICATION_HAS_COME_FOR_POST"
export const UPDATE_VIEWER_NOTIFI_POST = "UPDATE_VIEWER_NOTIFI_POST"
export const UPDATE_VIEWER_NOTIFI_TASK = "UPDATE_VIEWER_NOTIFI_TASK"

// POST
export const SET_LIST_POST = "SET_LIST_POST"
export const CREATE_LIST_POST = "CREATE_LIST_POST"
export const UPDATE_LIST_POST = "UPDATE_LIST_POST"
export const DELETE_LIST_POST = "DELETE_LIST_POST"
export const SET_NEW_POST = "SET_NEW_POST"


export const SET_CURRENT_POST = "SET_CURRENT_POST"
export const UPDATE_CURRENT_POST = "UPDATE_CURRENT_POST"
export const DELETE_CURRENT_POST = "DELETE_CURRENT_POST"


export const SET_CURRENT_LIST_COMMENT = "SET_CURRENT_LIST_COMMENT"
export const CREATE_CURRENT_LIST_COMMENT = "CREATE_CURRENT_LIST_COMMENT"
export const UPDATE_CURRENT_LIST_COMMENT = "UPDATE_CURRENT_LIST_COMMENT"
export const DELETE_CURRENT_LIST_COMMENT = "DELETE_CURRENT_LIST_COMMENT"

export const SET_CURRENT_POST_COMMENT = "SET_CURRENT_POST_COMMENT"
export const SET_IS_FOCUS_COMMENT = "SET_IS_FOCUS_COMMENT"
export const SET_SCROLLTO_COMMENT = "SET_SCROLLTO_COMMENT"
export const SET_IS_COMMENT = "SET_IS_COMMENT"
export const SET_IS_LAST_COMMENT = "SET_IS_LAST_COMMENT"

export const SET_CURRENT_LIST_COMMENT_CHILD = "SET_CURRENT_LIST_COMMENT_CHILD"
export const CREATE_CURRENT_LIST_COMMENT_CHILD = "CREATE_CURRENT_LIST_COMMENT_CHILD"
export const UPDATE_CURRENT_LIST_COMMENT_CHILD = "UPDATE_CURRENT_LIST_COMMENT_CHILD"
export const DELETE_CURRENT_LIST_COMMENT_CHILD = "DELETE_CURRENT_LIST_COMMENT_CHILD"

export const UPDATE_REACTION_POST = "UPDATE_REACTION_POST"
export const UPDATE_REACTION_CURRENT_POST = "UPDATE_REACTION_CURRENT_POST"


//post Search
export const SET_LIST_POST_SEARCH = "SET_LIST_POST_SEARCH"
export const CREATE_LIST_POST_SEARCH = "CREATE_LIST_POST_SEARCH"
export const UPDATE_REACTION_POST_SEARCH = "UPDATE_REACTION_POST_SEARCH"

// export const GET_MORE_REPLY_COMMENT = "GET_MORE_REPLY_COMMENT"
// export const SET_CURR_EDIT_POST = "SET_CURR_EDIT_POST"
// export const UPDATE_IMAGES_CURR_EDIT_POST = "UPDATE_IMAGES_CURR_EDIT_POST"
// export const REMOVE_IMAGES_CURR_EDIT_POST = "REMOVE_IMAGES_CURR_EDIT_POST"
// export const UPDATE_NEW_EDITED_LIST_POSTS = "UPDATE_NEW_EDITED_LIST_POSTS"
// export const UPDATE_CONTENT_CURR_EDIT_POST = "UPDATE_CONTENT_CURR_EDIT_POST"
// export const REMOVE_POST = "REMOVE_POST"
// export const CLEAR_CURR_SEE_POST = "CLEAR_CURR_SEE_POST"
// export const REMOVE_COMMENT = "REMOVE_COMMENT"
// export const UPDATE_COMMENT = "UPDATE_COMMENT"
// export const UPDATE_LIKE_COUNT_POST = "UPDATE_LIKE_COUNT_POST"
// export const UPDATE_CURR_SEE_POST_COMMENT = "UPDATE_CURR_SEE_POST_COMMENT"
// export const REMOVE_VIDEO_CURR_EDIT_POST = "REMOVE_VIDEO_CURR_EDIT_POST"
// export const REMOVE_FILE_CURR_EDIT_POST = "REMOVE_FILE_CURR_EDIT_POST"
// export const UPDATE_FILES_CURR_EDIT_POST = "UPDATE_FILES_CURR_EDIT_POST"
// export const UPDATE_VIDEOS_CURR_EDIT_POST = "UPDATE_VIDEOS_CURR_EDIT_POST"


// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOG_OUT = 'LOG_OUT'
export const CLEAR_STORE_REDUX = 'CLEAR_STORE_REDUX'
export const CHECK_AUTH_PROCESSING = 'CHECK_AUTH_PROCESSING'


// SYSTEM   
export const SET_LIST_MEMBERS_OF_SYSTEM = "SET_LIST_MEMBERS_OF_SYSTEM"
export const SAVE_LIST_USERS_IN_APP = "SAVE_LIST_USERS_IN_APP"
export const SAVE_LIST_USERS_ONLINE = "SAVE_LIST_USERS_ONLINE"
export const NEW_USER_ONLINE = "NEW_USER_ONLINE"
export const NEW_USER_OFFLINE = "NEW_USER_OFFLINE"

// NETWORK
export const SET_NETWORK_INFO = "SET_NETWORK_INFO"

// MESSAGE
export const SET_LIST_LASTED_MESSAGES = "SET_LIST_LASTED_MESSAGES"
export const UPDATE_LIST_LASTED_MESSAGES = "UPDATE_LIST_LASTED_MESSAGES"
export const GET_NEW_MESSAGE = "GET_NEW_MESSAGE"
export const UPDATE_VIEWER_MESSAGE = "UPDATE_VIEWER_MESSAGE"
export const SAVE_INFO_CURR_CHATTING = 'SAVE_INFO_CURR_CHATTING'
export const SAVE_LIST_MESSAGE_CURR_CHATTING = 'SAVE_LIST_MESSAGE_CURR_CHATTING'
export const CLEAR_DATA_CURR_CHATTING = 'CLEAR_DATA_CURR_CHATTING'
export const GET_MORE_MESSAGE = 'GET_MORE_MESSAGE'
export const REMOVE_MEMBERS_CURR_CHATTING = 'REMOVE_MEMBERS_CURR_CHATTING'
export const UPDATE_MEMBERS_CURR_CHATTING = 'UPDATE_MEMBERS_CURR_CHATTING'
export const GET_NEWEST_MESSAGE = 'GET_NEWEST_MESSAGE'
export const UPDATE_STATUS_ACTIVE_MESSAGE = 'UPDATE_STATUS_ACTIVE_MESSAGE'
export const UPDATE_SPECIFIC_MESSAGE = 'UPDATE_SPECIFIC_MESSAGE'

// BOOKING
export const SAVE_LIST_BRANCH = "SAVE_LIST_BRANCH"
export const SAVE_LIST_DOCTOR = "SAVE_LIST_DOCTOR"




// ME
export const EMPLOYEE_UPDATE_AVATAR = "EMPLOYEE_UPDATE_AVATAR"

// ERROR
export const NEW_ERROR = "NEW_ERROR" 

// NEWS
export const SET_LIST_NEWS = "SET_LIST_NEWS"
export const SET_NEWS_HOME = "SET_NEWS_HOME"


//SERVICES
export const SET_SERVICE= 'SET_SERVICE'
export const SET_SERVICE_HOME= 'SET_SERVICE_HOME'
//SERVICES GROUP
export const SET_SERVICE_GROUP= 'SET_SERVICE_GROUP'

//PRODUCT
export const SET_PRODUCT= 'SET_PRODUCT'
export const SET_PRODUCT_HOME= 'SET_PRODUCT_HOME'
//PRODUCT GROUP
export const SET_PRODUCT_GROUP= 'SET_PRODUCT_GROUP'


//infoUser
export const SET_INFO_TREATMENT = 'SET_INFO_TREATMENT'
export const SET_INFO_ORDER = 'SET_INFO_ORDER'
export const SET_INFO_ORDER_SERVICE = 'SET_INFO_ORDER_SERVICE'
export const SET_INFO_PAYMENT = 'SET_INFO_PAYMENT'
export const SET_INFO_DEPOSIT = 'SET_INFO_DEPOSIT'
export const SET_INFO_MEDICAL_PRESCRIPTION = 'SET_INFO_MEDICAL_PRESCRIPTION'
export const SET_INFO_COLLAB_STATISTIC = 'SET_INFO_COLLAB_STATISTIC'
export const SET_CODE_AFFILIATE = 'SET_CODE_AFFILIATE'
export const SET_NOTICE_NOT_AUTO_SHOW_TUT = 'SET_NOTICE_NOT_AUTO_SHOW_TUT'
export const SET_NOTICE_NOT_AUTO_SHOW_TUT_CREATE_BK = 'SET_NOTICE_NOT_AUTO_SHOW_TUT_CREATE_BK'

//Orther
export const SET_ASSET_GROUP = 'SET_ASSET_GROUP'
export const SET_ASSET = 'SET_ASSET'

export const SAVE_LIST_NOTI="SAVE_LIST_NOTI"
export const ADD_NEW_PARTNER_NOTI = "ADD_NEW_PARTNER_NOTI"
export const SHOW_LIST_ALL_NOTI = "SHOW_LIST_ALL_NOTI"
export const SHOW_BAGED_DIARY = "SHOW_BAGED_DIARY"
export const SET_DATA_BAGED_DIARY = "SET_DATA_BAGED_DIARY"
export const UPDATE_SEEN_LIST_NOTI = "UPDATE_SEEN_LIST_NOTI"
export const SHOW_MODAL_NOTI = "SHOW_MODAL_NOTI"
export const SHOW_MODAL_REQUIRE_LOGIN = "SHOW_MODAL_REQUIRE_LOGIN"
export const SHOW_MODAL_REQUIRE_AVATAR = "SHOW_MODAL_REQUIRE_AVATAR"
export const SET_ENDED_CALLING = "SET_ENDED_CALLING"

//Branch
export const SET_LIST_BRANCH = 'SET_LIST_BRANCH'
export const SET_LIST_DOCTOR='SET_LIST_DOCTOR'

//Diary
export const SET_LIST_TREATMENT_DIARY = 'SET_LIST_TREATMENT_DIARY'
export const SET_LIST_TREATMENT_DIARY_SERVICE = 'SET_LIST_TREATMENT_DIARY_SERVICE'
export const SET_CURRENT_TREATMENT_DIARY = 'SET_CURRENT_TREATMENT_DIARY'
export const CLEAR_CURRENT_TREATMENT_DIARY = 'CLEAR_CURRENT_TREATMENT_DIARY'
export const UPDATE_CURRENT_TREATMENT_DIARY = 'UPDATE_CURRENT_TREATMENT_DIARY'
export const SET_LIST_TREATMENT_DIARY_DETAIL = 'SET_LIST_TREATMENT_DIARY_DETAIL'

export const SET_LIST_PARTNER_DIARY = 'SET_LIST_PARTNER_DIARY'
export const CREATE_PARNERT_DIARY = 'CREATE_PARNERT_DIARY'
export const UPDATE_PARNERT_DIARY = 'UPDATE_PARNERT_DIARY'
export const SET_CURRENT_PARTNER_DIARY = 'SET_CURRENT_PARTNER_DIARY'
export const SET_CURRENT_PARTNER_DIARY_DAILY = 'SET_CURRENT_PARTNER_DIARY_DAILY'
export const CREATE_PARNERT_DIARY_DAILY = 'CREATE_PARNERT_DIARY_DAILY'
export const UPDATE_PARNERT_DIARY_DAILY = 'UPDATE_PARNERT_DIARY_DAILY'
export const SET_CURRENT_PARTNER_DIARY_DAILY_UPDATE = 'SET_CURRENT_PARTNER_DIARY_DAILY_UPDATE'

// LOSE WEIGHT
export const SET_DATE_FILTER_TRACKING_WEIGHT = 'SET_DATE_FILTER_TRACKING_WEIGHT'
export const SET_DATA_TRACKING_WEIGHT = 'SET_DATA_TRACKING_WEIGHT'
export const SET_DATA_MENU_FOOD = 'SET_DATA_MENU_FOOD'
export const ADD_MORE_DATA_MENU_FOOD = 'ADD_MORE_DATA_MENU_FOOD'
export const REMOVE_DATA_MENU_FOOD = 'REMOVE_DATA_MENU_FOOD'
export const UPDATE_DATA_TRACKING_WEIGHT = 'UPDATE_DATA_TRACKING_WEIGHT'
export const UPDATE_DATA_TRACKING_WEIGHT_GOAL = 'UPDATE_DATA_TRACKING_WEIGHT_GOAL'
export const SET_DATA_MENU_ACTIVITY = 'SET_DATA_MENU_ACTIVITY'
export const ADD_MORE_DATA_MENU_ACTIVITY = 'ADD_MORE_DATA_MENU_ACTIVITY'
export const REMOVE_DATA_MENU_ACTIVITY = 'REMOVE_DATA_MENU_ACTIVITY'
export const SAVE_DATA_TRACKING_WEIGHT_GOAL = 'SAVE_DATA_TRACKING_WEIGHT_GOAL'
export const UPDATE_DATA_TRACKING_WATER_GOAL = 'UPDATE_DATA_TRACKING_WATER_GOAL'

// WALLET
export const SET_DATA_WALLET = 'SET_DATA_WALLET'
export const SHOW_MODAL_GET_REWARD = 'SHOW_MODAL_GET_REWARD'


export const NEW_MSG_REACTION = "NEW_MSG_REACTION"
export const SET_NEW_PLAY_TRACK = "SET_NEW_PLAY_TRACK"
export const SET_STATUS_PLAYING_TRACK = "SET_STATUS_PLAYING_TRACK"
export const EXPANDED = "EXPANDED"